on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]

name: Create RPM Release

jobs:
  call-rpmbuild-workflow:
    uses: fmidev/github-actions-workflows/.github/workflows/rpmbuild-workflow.yaml@main
    with:
      rpm_base_image: rockylinux/rockylinux:8
      rpm_spec_file: fminc.spec
      rpm_additional_repositories: "epel-release,https://download.fmi.fi/smartmet-open/rhel/8/x86_64/smartmet-open-release-latest-8.noarch.rpm"
      rpm_enable_repositories: powertools
      build_image: false
    secrets:
      RPM_API_HOST: ${{ secrets.RPM_API_HOST }}
      RPM_API_USER: ${{ secrets.RPM_API_USER }}
      RPM_API_PASS: ${{ secrets.RPM_API_PASS }}
